### ISSUE TITLE
in RING_BUFFER_ARRAYS mode,RingBuffer_t->place will overflow.

### ISSUE THREAD

**Issue by q601904795** [magiczny-kacper/RingBuffer#1]
When I fill the ring, I use RingReadByte (); to read a piece of data.
Then I use RingWriteByte() to populate the ring with a new piece of data,and the ringBuffer_t ->place overflowed.

Sorry, I am a Chinese and my English is poor.

**Comment by magiczny-kacper** [comment]
@q601904795 can you provide me some code, to reproduce your error?
